export const DIFFICULTY = {
  easy: {
    label: 'Easy',
    duration: 45,
    maxCorrect: 3,
    distractors: 6,
    speedMultiplier: 0.6,
    correctPoints: 5,
    wrongPenalty: 2,
    color: '#22c55e',
    targetMin: 6,
    targetMax: 20,
    operations: ['add', 'sub'],
  },
  medium: {
    label: 'Medium',
    duration: 30,
    maxCorrect: 4,
    distractors: 10,
    speedMultiplier: 1.0,
    correctPoints: 10,
    wrongPenalty: 5,
    color: '#f59e0b',
    targetMin: 12,
    targetMax: 50,
    operations: ['add', 'sub', 'mul'],
  },
  hard: {
    label: 'Hard',
    duration: 20,
    maxCorrect: 5,
    distractors: 14,
    speedMultiplier: 1.6,
    correctPoints: 15,
    wrongPenalty: 8,
    color: '#ef4444',
    targetMin: 20,
    targetMax: 100,
    operations: ['add', 'sub', 'mul', 'div'],
  },
};
