export const GRADES = {
  K: {
    label: 'Kindergarten',
    shortLabel: 'K',
    skillDesc: 'Simple addition · sums up to 8',
    duration: 90,
    maxCorrect: 2,
    distractors: 3,
    speedMultiplier: 0.35,
    correctPoints: 5,
    wrongPenalty: 0,
    color: '#FF6B6B',
    targetMin: 3,
    targetMax: 8,
    operations: ['add'],
  },
  '1': {
    label: '1st Grade',
    shortLabel: '1st',
    skillDesc: 'Addition & subtraction · up to 15',
    duration: 75,
    maxCorrect: 2,
    distractors: 4,
    speedMultiplier: 0.4,
    correctPoints: 5,
    wrongPenalty: 0,
    color: '#FF8E53',
    targetMin: 5,
    targetMax: 15,
    operations: ['add', 'sub'],
  },
  '2': {
    label: '2nd Grade',
    shortLabel: '2nd',
    skillDesc: 'Addition & subtraction · up to 25',
    duration: 65,
    maxCorrect: 3,
    distractors: 5,
    speedMultiplier: 0.5,
    correctPoints: 5,
    wrongPenalty: 1,
    color: '#FFD93D',
    targetMin: 8,
    targetMax: 25,
    operations: ['add', 'sub'],
  },
  '3': {
    label: '3rd Grade',
    shortLabel: '3rd',
    skillDesc: 'Add, subtract & multiply',
    duration: 55,
    maxCorrect: 3,
    distractors: 6,
    speedMultiplier: 0.6,
    correctPoints: 8,
    wrongPenalty: 2,
    color: '#6BCB77',
    targetMin: 10,
    targetMax: 40,
    operations: ['add', 'sub', 'mul'],
  },
  '4': {
    label: '4th Grade',
    shortLabel: '4th',
    skillDesc: 'Add, subtract & multiply · bigger numbers',
    duration: 50,
    maxCorrect: 3,
    distractors: 7,
    speedMultiplier: 0.7,
    correctPoints: 8,
    wrongPenalty: 2,
    color: '#4ECDC4',
    targetMin: 15,
    targetMax: 60,
    operations: ['add', 'sub', 'mul'],
  },
  '5': {
    label: '5th Grade',
    shortLabel: '5th',
    skillDesc: 'All four operations including division',
    duration: 45,
    maxCorrect: 4,
    distractors: 8,
    speedMultiplier: 0.8,
    correctPoints: 10,
    wrongPenalty: 3,
    color: '#45B7D1',
    targetMin: 20,
    targetMax: 80,
    operations: ['add', 'sub', 'mul', 'div'],
  },
  '6': {
    label: '6th Grade',
    shortLabel: '6th',
    skillDesc: 'All operations · larger numbers',
    duration: 40,
    maxCorrect: 4,
    distractors: 9,
    speedMultiplier: 0.9,
    correctPoints: 10,
    wrongPenalty: 4,
    color: '#96CEB4',
    targetMin: 30,
    targetMax: 100,
    operations: ['add', 'sub', 'mul', 'div'],
  },
  '7': {
    label: '7th Grade',
    shortLabel: '7th',
    skillDesc: 'All operations · faster pace',
    duration: 35,
    maxCorrect: 4,
    distractors: 10,
    speedMultiplier: 1.0,
    correctPoints: 12,
    wrongPenalty: 5,
    color: '#C7A4FF',
    targetMin: 40,
    targetMax: 120,
    operations: ['add', 'sub', 'mul', 'div'],
  },
  '8': {
    label: '8th Grade',
    shortLabel: '8th',
    skillDesc: 'All operations · tougher challenge',
    duration: 32,
    maxCorrect: 4,
    distractors: 11,
    speedMultiplier: 1.1,
    correctPoints: 12,
    wrongPenalty: 5,
    color: '#A4C2FF',
    targetMin: 50,
    targetMax: 150,
    operations: ['add', 'sub', 'mul', 'div'],
  },
  '9': {
    label: '9th Grade',
    shortLabel: '9th',
    skillDesc: 'Speed arithmetic',
    duration: 28,
    maxCorrect: 5,
    distractors: 12,
    speedMultiplier: 1.2,
    correctPoints: 15,
    wrongPenalty: 6,
    color: '#FF9AA2',
    targetMin: 60,
    targetMax: 175,
    operations: ['add', 'sub', 'mul', 'div'],
  },
  '10': {
    label: '10th Grade',
    shortLabel: '10th',
    skillDesc: 'Speed arithmetic · bigger range',
    duration: 25,
    maxCorrect: 5,
    distractors: 13,
    speedMultiplier: 1.3,
    correctPoints: 15,
    wrongPenalty: 7,
    color: '#FFB7B2',
    targetMin: 75,
    targetMax: 200,
    operations: ['add', 'sub', 'mul', 'div'],
  },
  '11': {
    label: '11th Grade',
    shortLabel: '11th',
    skillDesc: 'Expert arithmetic',
    duration: 22,
    maxCorrect: 5,
    distractors: 14,
    speedMultiplier: 1.45,
    correctPoints: 15,
    wrongPenalty: 8,
    color: '#FF6F91',
    targetMin: 100,
    targetMax: 225,
    operations: ['add', 'sub', 'mul', 'div'],
  },
  '12': {
    label: '12th Grade',
    shortLabel: '12th',
    skillDesc: 'Maximum challenge',
    duration: 20,
    maxCorrect: 5,
    distractors: 14,
    speedMultiplier: 1.6,
    correctPoints: 15,
    wrongPenalty: 8,
    color: '#E74C3C',
    targetMin: 120,
    targetMax: 250,
    operations: ['add', 'sub', 'mul', 'div'],
  },
};

export const GRADE_KEYS = ['K', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'];
